import './globals.css'
import { Montserrat } from 'next/font/google'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'MediNest',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <html lang="en" className='h-screen'>
        <body className={montserrat.className}>
          {children}
          </body>
      </html>
  )
}
